language: erlang
otp_release:
  - 18.2.1

sudo: required

script: cd tests/rustmk_demo && make tests

before_install:
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh

before_script: 
  - kerl list installations
